import numpy as np

In [1]:
import numpy as np

Array of 10 zeros

In [2]:
zero=np.zeros(10)

In [3]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Array of 10 ones

In [4]:
one=np.ones(10)


In [5]:
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Array of 10 fives

In [6]:
five=np.ones(10)*5

In [7]:
five

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of all even integers from 10 to 50

In [8]:
a=np.arange(10,51,2)

In [9]:
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from  0 to 8

In [10]:
a = np.arange(0,9).reshape(3,3)
   

In [11]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create 3x3 identity matrix 

In [12]:
a = np.identity(3)

In [13]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Generate a random number between 0 and 1

In [14]:
x = np.random.rand()

In [15]:
x

0.5945675643660239

Use a numpy to generate array of 25 random numbers sampled from a standard normal distribution

In [16]:
b = np.random.standard_normal(25)

In [17]:
b

array([ 1.31120099,  0.11734406, -1.67151085,  0.12229985,  0.21485284,
       -1.45743018, -0.75711846, -0.20362098,  0.67513813, -2.20247348,
        0.34621103, -0.44290886,  1.36984031,  0.39122764,  2.22017397,
       -0.44169532,  1.05948637, -0.68584725, -0.60213366,  0.39273463,
       -1.34403888,  0.69262257, -1.64928243, -1.69045602,  1.47553052])

Array of 20 linearly spaced points between 0 and 1

In [18]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Numpy Indexing and Selection

In [19]:
mat = np.arange(1,26).reshape(5,5)

In [20]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
mat[2:,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [22]:
mat[3,4]

20

In [23]:
mat[0:,1:2]

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [24]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [25]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])